[package]
name = "simple-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

[dependencies.opcua]
path = "../../common/rust/opcua/lib"
version = "0.13.0" # OPCUARustVersion
features = ["client", "console-logging"]
